#!/bin/fish
# This file was generated by ChatGPT Dec 15 Version.

# Check if Bluetooth is enabled
if not bluetoothctl show | grep -q "Powered: yes"
    echo "Bluetooth is not enabled. Please enable Bluetooth and try again."
    return 1
end

# Get the MAC address of the headset
set -l headset_mac (bluetoothctl devices | grep -Eo "([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})" | head -1)

# Connect to the headset
bluetoothctl connect $headset_mac
