#!/bin/bash
# This file was generated by ChatGPT Dec 15 Version.

# Check if Bluetooth is enabled
if ! bluetoothctl show | grep -q "Powered: yes"; then
    echo "Bluetooth is not enabled. Please enable Bluetooth and try again."
    exit 1
fi

# Get the MAC address of the headset
headset_mac=$(bluetoothctl devices | grep -Eo "([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})" | head -1)

# Connect to the headset
bluetoothctl connect "$headset_mac"
