// This file was generated by ChatGPT Dec 15 Version.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main(void) {
    // Check if Bluetooth is enabled
    FILE *fp = popen("bluetoothctl show", "r");
    if (fp == NULL) {
        perror("Failed to run command");
        exit(1);
    }
    char buffer[256];
    int bluetooth_enabled = 0;
    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
        if (strstr(buffer, "Powered: yes")) {
            bluetooth_enabled = 1;
            break;
        }
    }
    pclose(fp);
    if (!bluetooth_enabled) {
        printf("Bluetooth is not enabled. Please enable Bluetooth and try again.\n");
        exit(1);
    }

    // Get the MAC address of the headset
    fp = popen("bluetoothctl devices", "r");
    if (fp == NULL) {
        perror("Failed to run command");
        exit(1);
    }
    char headset_mac[20];
    while (fgets(buffer, sizeof(buffer), fp) != NULL) {
        if (sscanf(buffer, "%*s %19s", headset_mac) == 1) {
            break;
        }
    }
    pclose(fp);

    // Connect to the headset
    char command[256];
    sprintf(command, "bluetoothctl connect %s", headset_mac);
    fp = popen(command, "r");
    if (fp == NULL) {
        perror("Failed to run command");
        exit(1);
    }
    pclose(fp);

    return 0;
}
